import type { TestCase } from "@content/_authoring/types";

export const functionName = "parseSetCookie";

export const tests: TestCase[] = [
  {
    name: "a well-configured session cookie has no warnings",
    args: ["__Host-sid=abc123; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=3600"],
    expected: {
      name: "__Host-sid",
      value: "abc123",
      domain: null,
      path: "/",
      maxAge: 3600,
      httpOnly: true,
      secure: true,
      sameSite: "Lax",
      warnings: [],
    },
  },
  {
    name: "a bare cookie gets defaults and a HttpOnly warning",
    args: ["theme=dark"],
    expected: {
      name: "theme",
      value: "dark",
      domain: null,
      path: null,
      maxAge: null,
      httpOnly: false,
      secure: false,
      sameSite: null,
      warnings: ["Missing HttpOnly"],
    },
  },
  {
    name: "attribute names and SameSite values are case-insensitive",
    args: ["sid=x; httponly; SECURE; samesite=strict; path=/app"],
    expected: {
      name: "sid",
      value: "x",
      domain: null,
      path: "/app",
      maxAge: null,
      httpOnly: true,
      secure: true,
      sameSite: "Strict",
      warnings: [],
    },
  },
  {
    name: "SameSite=None without Secure is flagged",
    args: ["track=1; SameSite=None; HttpOnly"],
    expected: {
      name: "track",
      value: "1",
      domain: null,
      path: null,
      maxAge: null,
      httpOnly: true,
      secure: false,
      sameSite: "None",
      warnings: ["SameSite=None requires Secure"],
    },
  },
  {
    name: "values may contain =",
    args: ["token=a=b==; Secure; HttpOnly; Path=/"],
    expected: {
      name: "token",
      value: "a=b==",
      domain: null,
      path: "/",
      maxAge: null,
      httpOnly: true,
      secure: true,
      sameSite: null,
      warnings: [],
    },
  },
  {
    name: "a __Host- cookie with a Domain is flagged, and Expires is ignored",
    args: ["__Host-sid=q; Domain=shop.test; Path=/; Secure; HttpOnly; Expires=Wed, 21 Oct 2026 07:28:00 GMT"],
    expected: {
      name: "__Host-sid",
      value: "q",
      domain: "shop.test",
      path: "/",
      maxAge: null,
      httpOnly: true,
      secure: true,
      sameSite: null,
      warnings: ["__Host- cookies need Secure, Path=/ and no Domain"],
    },
  },
  {
    name: "Max-Age=0 deletes the cookie (still parsed as 0)",
    args: ["sid=; Max-Age=0; Path=/"],
    expected: {
      name: "sid",
      value: "",
      domain: null,
      path: "/",
      maxAge: 0,
      httpOnly: false,
      secure: false,
      sameSite: null,
      warnings: ["Missing HttpOnly"],
    },
    hidden: true,
  },
  {
    name: "several warnings are listed in order",
    args: ["__Host-x=1; SameSite=none"],
    expected: {
      name: "__Host-x",
      value: "1",
      domain: null,
      path: null,
      maxAge: null,
      httpOnly: false,
      secure: false,
      sameSite: "None",
      warnings: ["Missing HttpOnly", "SameSite=None requires Secure", "__Host- cookies need Secure, Path=/ and no Domain"],
    },
    hidden: true,
  },
];
